# Generated by Django 5.0.1 on 2024-01-17 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_delete_material_form_status_alter_form_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
